# Generated by Django 4.2.7 on 2024-01-22 11:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Introduce un identificador numérico', primary_key=True, serialize=False)),
                ('letra', models.CharField(help_text='Introduce una letra', max_length=1, unique=True, verbose_name='Letra')),
            ],
            options={
                'ordering': ['letra'],
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Introduce un identificador numérico', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Introduce un nombre', max_length=120, verbose_name='Nombre')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Registrado')),
                ('estado', models.CharField(blank=True, choices=[('r', 'Revisión'), ('a', 'Aprobado')], default='r', help_text='Selecciona un estado', max_length=1, verbose_name='Estado')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Introduce un identificador numérico', primary_key=True, serialize=False)),
                ('palabra', models.CharField(help_text='Introduce una palabra', max_length=31, verbose_name='Palabra')),
                ('significado', models.TextField(default='', help_text='Introduce el significado', max_length=352, verbose_name='Significado')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Registrada')),
                ('estado', models.CharField(blank=True, choices=[('r', 'Revisión'), ('a', 'Aprobada')], default='r', help_text='Selecciona un estado', max_length=1, verbose_name='Estado')),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('letra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='refran.letra')),
                ('origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='refran.origen')),
            ],
            options={
                'ordering': ['palabra', 'letra', 'origen', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Refran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Introduce un identificador numérico', primary_key=True, serialize=False)),
                ('dicho', models.TextField(help_text='Introduce el refrán', max_length=191, verbose_name='Refrán')),
                ('explicacion', models.TextField(help_text='Introduce una explicación', max_length=251, verbose_name='Explicación')),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Registrado')),
                ('fechaaprobacion', models.DateField(blank=True, null=True, verbose_name='Aprobado')),
                ('fechapublicacion', models.DateField(blank=True, null=True, verbose_name='Publicado')),
                ('estado', models.CharField(blank=True, choices=[('r', 'Revisión'), ('a', 'Aprobado'), ('p', 'Publicado')], default='r', help_text='Selecciona un estado', max_length=1, verbose_name='Estado')),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('letra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='refran.letra')),
                ('origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='refran.origen')),
                ('palabra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='refran.palabra')),
            ],
            options={
                'ordering': ['palabra', 'fecha', 'fechaaprobacion', 'fechapublicacion'],
            },
        ),
    ]
